### ISSUE TITLE
Install dont work in Plugin Admin of NotePad++.

### ISSUE THREAD

**Issue by boubou** [Dook1/Bookmarks-Dook#1]

**Comment by sboulianne** [comment]
Checksum is bad.

**Comment by Dook1** [comment]
Download from here: https://github.com/Dook1/Bookmarks-Dook/releases
and unpack into plugins\BookmarksDook
Or wait for the next release Plugin Admin.

**Comment by sboulianne** [comment]
When do you think you will release a new version ?

**Comment by Dook1** [comment]
I don't know. Ask here - https://notepad-plus-plus.org/community/topic/16566/support-for-plugins-admin-npppluginlist
