### ISSUE TITLE
Bookmarks panel has no focus when opened

### ISSUE THREAD

**Issue by kiyn** [Dook1/Bookmarks-Dook#10]
Bookmarks panel, if docked, has no focus when opened, neither the editor has it.
The focus remains on the window title bar.
I hope the focus will be set to the panel in the future releases.
Thanks

**Comment by Dook1** [comment]
Try it:
https://github.com/Dook1/Bookmarks-Dook/releases/download/2.3.1.64b/BookmarksDook.64.2.3.1.zip
https://github.com/Dook1/Bookmarks-Dook/releases/download/2.3.1.32b/BookmarksDook.32.2.3.1.zip

After opening the panel, press DOWN key.

**Comment by kiyn** [comment]
Great!
Thank you.

Very convenient, but I found a bug in the new version. 
It no longer load text settings.
It does only if you open the Options window after every n++ start.
Tested 2.3.1.64b with Notepad++ v7.9.5.

I also noticed that the latest version is not at the top of github releases list, due to the way they have been named. 

I love your plugin and I use it everyday.
I hope you will continue to find the time to support and maybe improve it.
Unfortunately I cannot help, not having knowledge of C ++.

**Comment by Dook1** [comment]
Fixed in 2.3.2
https://github.com/Dook1/Bookmarks-Dook/releases/download/23264b/BookmarksDook.64.2.3.2.zip
https://github.com/Dook1/Bookmarks-Dook/releases/download/23232b/BookmarksDook.32.2.3.2.zip

**Comment by kiyn** [comment]
Now everything looks ok.
Do you think it would be useful to implement enter press on a bookmark to switch focus to the editor while the panel remains open?

**Comment by kiyn** [comment]
I'm sorry, I just noticed that the line number in the panel starts from zero and therefore falls behind by one in every line.

**Comment by Dook1** [comment]
"Enter press" added & "line number" fixed in 2.3.3
https://github.com/Dook1/Bookmarks-Dook/releases/download/23364b/BookmarksDook.64.2.3.3.zip
https://github.com/Dook1/Bookmarks-Dook/releases/download/23332b/BookmarksDook.32.2.3.3.zip
