### ISSUE TITLE
AutoSave Bookmarks as a file for backup purposes

### ISSUE THREAD

**Issue by Sarge2013** [Dook1/Bookmarks-Dook#12]
Thanks a lot for the functional and convenient plugin for NPP !
I'm just did not find any setting where we could save a backup copy of the bookmarks (all available...or from current session)
It scares if you have created hundreds bookmarks for many files but the ones can be lost suddenly...you know system failures happens...
I hope you could add such a feature to a next release of Bookmark-Dook,
Thx for your attention, good luck !
Serge

**Comment by Dook1** [comment]
I think this is more related to the main functionality of Noteapd. Try to request this feature here:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues

**Comment by Sarge2013** [comment]
I think you're right, so will repeat a similar request there asap.
Do you know - where NPP saves the bookmarks now ? 
As it definitely not a file - somewhere in MS Registry ?
Thx in advance for a comment !
Brgrds, Serge

**Comment by Dook1** [comment]
C:\Users\{USERNAME}\AppData\Roaming\Notepad++\session.xml

<Mark line="17" />

**Comment by Sarge2013** [comment]
Thank you, I've got the idea !
