### ISSUE TITLE
Change focus from text window to BookmarksDook

### ISSUE THREAD

**Issue by Sarge2013** [Dook1/Bookmarks-Dook#13]
Hello,
I found when BookmarksDook active - pressing ENTER will change the focus from BookmarksDook to main text window.
Is there any keyboard shortcut for a "back" operation ? (now it can be done only by mouse click)
I mean when main text window active - press CTRL+Something (or any other shortcut) - and focus will be changed from text window to BookmarksDook window.
IMHO - it could be very convenient for fast navigation through files with bookmarks.
Thank you for your attention and comment !
Best regards,
Serge

**Comment by Dook1** [comment]
Okay, I'll add that to the next version.

**Comment by Sarge2013** [comment]
Thanks a lot ! Waiting with great impatience :)

**Comment by Sarge2013** [comment]
Let me add one more detail relating to the same issue regarding focus.
Unfortunately there is no a Setting parameter what allows to set color not for background of BookmarksDook - but exactly for Label at the top - please, see two small screenshots attached
![active_BookmarksDook](https://user-images.githubusercontent.com/5161375/145675754-2096ffbe-0749-452e-b947-e9841b16d896.png)
![inactive_BookmarksDook](https://user-images.githubusercontent.com/5161375/145675755-b61f731b-4ec0-4f61-9902-a673984c565d.png)

As you can see - active BookmarksDook Label at the top has a dark-blue color what is not "catching-eye" - but only color of this Label visually shows - is BookmarksDook active or not.
As to me - I'd set the one to RED for myself to avoid any doubt where right now the active focus is...

I don't know is it possible to add such a parameter to Plugin Options as "Top Label background color" - but IMHO it also could be a good idea for better visualization,

Thanks again for your attention !
Best regards,
Serge

**Comment by Dook1** [comment]
It's impossible. These colors are determined by the current Windows theme.

**Comment by Dook1** [comment]
You can change these colors yourself in the Windows settings.

**Comment by Sarge2013** [comment]
That's a pity, of course :( but reality is reality...will try to follow your advice., thank you !
In the meantime (again about focus)  - may I ask why clicking on a BookmarksDook bookmark open the one in the bottom of text window ? 
If you go up through BookmarksDook tree - the one at the top, when go down through the same tree - then at the bottom.
I suppose the opened bookmark should be always at the top of text window by default...again for best "eye-view"...
Hopefully you will agree to fix it at a new version,
Best regards,
Serge

**Comment by Dook1** [comment]
This is not controlled by my plugin, but by Notepad+ itself, most likely even by Scintilla.

**Comment by Sarge2013** [comment]
Thank you for the hint ! I'll try to dig there...
But about background color mentioned above (what you say determined by Windows 10 theme) - I give up ! :))
Very time-wasting to find a solution (more than that unlikely it's good to change ALL backgrounds if I need just one under N++ exactly for BookmarksDook)

IF POSSIBLE - could you consider an idea to change background color of BookmarksDook depending on active/inactive state ?
I mean under Options - Bookmarks Panel - add option set background color for active/inactive.
At-least - I suppose this under your plugin control and also very "attention-catching" visualization.
Thank you in advance for the improvements discussed here !
Best regards,
Serge

**Comment by Dook1** [comment]
I'll think about it.

**Comment by Sarge2013** [comment]
Thanks for your attention, waiting for the new version !

**Comment by Sarge2013** [comment]
Just For Your Consideration
The question to change BookmarksDook background depending on active/inactive state just because of Ctrl-Tab to switch between opened files - because when you switch by Ctrl-Tab FROM ANY FILE WITHOUT BOOKMARKS to ANY FILE WITH BOOKMARKS - focus automatically set to BookmarksDook panel (active).
So if you forgot to press ENTER to activate main text panel - any keyboard action will be performed at BookmarksDook panel and you will lose where you were on main text panel. 
Sometimes very difficult to control yourself "where is the active focus now"
There are two solutions here
1 - set various color background for active/inactive state - as a bright color hint "do not forgot to press Enter to return to main text panel"
2 - or fix somehow the behaviour mentioned above - focus ALWAYS must be on main text panel switching between the opened files WITH/WITHOUT bookmarks (until by cursor or by promised shortcut you make BookmarksDook active)

I just would like to explain that active/inactive color background is not just for "nice view" - but because of loosing focus from main text panel as described above. 
May be you just can fix it like in Variant 2 - and no necessity for various colors then.

Best regards,

**Comment by Dook1** [comment]
Already fixed. Variant 2

**Comment by Sarge2013** [comment]
Excellent ! May be with "back" shortcut too ? :)
But how to update the plugin ? Standard N++ update says nothing new, I have latest 8.1.9.3 and BookmarksDook 2.3.3 - and at
https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x86.md
also same version...

**Comment by Dook1** [comment]
No "back shortcut" yet. I fixed variant 2 a long time ago, I just forgot to upload it. Everything will be in the next version.

**Comment by Sarge2013** [comment]
Thanks a lot ! Waiting with great impatience ! :)

**Comment by Sarge2013** [comment]
Hello,
a release of next version with "keyboard shortcut to BookmarkDook panel" (and may be other improvements) is your good will :) so only you know when it will happen.
Sorry for an impatience :) but really annoying to lose focus while moving between opened files by Ctrl-Tab...no chance always keep an "eye-control" - and very often lose a line where active edit goes...every time enforced to use search to find where it was...

May be right now you could upload at-least a ready version where already fixed a bug with active window using Ctrl-Tab ? (discussed above)
You said this version is ready long time ago just not uploaded yet...
Thank you for your attention !

**Comment by Dook1** [comment]
https://github.com/Dook1/Bookmarks-Dook/releases/download/2.3.4.64b/BookmarksDook.64.2.3.4.zip
https://github.com/Dook1/Bookmarks-Dook/releases/download/2.3.4.32b/BookmarksDook.32.2.3.4.zip

**Comment by Sarge2013** [comment]
Thank you VERY MUCH !
I'm using this version during 1 hour - and already really big relief ! at-last no inner tension to control "where am I now ?" :)))
Wish you the best coming Christmas and still hope for a small Christmas miracle about newest version with "keyboard shortcut to activate BookmarkDook panel from active text window" :) as to me this is the last important improvement for fastest navigation.
But even now - thanks again for the version 2.3.4 !
Have a nice day !

**Comment by Dook1** [comment]
I wish you the same. And here's your Christmas present). Alt+Enter - switch to bookmarks panel:
https://github.com/Dook1/Bookmarks-Dook/releases/download/2.3.5.64b/BookmarksDook.64.2.3.5.zip
https://github.com/Dook1/Bookmarks-Dook/releases/download/2.3.5.32b/BookmarksDook.32.2.3.5.zip

**Comment by Sarge2013** [comment]
**Now The Christmas really came !** 
Just for your information
- Google Chrome is nervous about downloading - I suppose because DLL file inside - so better upload to 
https://github.com/notepad-plus-plus/nppPluginList/blob/master/doc/plugin_list_x86.md to include your excellent update to enjoy for all N++ users (so I've used Firefox)
- I did not find shortcut key ALT-ENTER work by default, but no problem to set using N++ Settings - Shortcut Mapper
Thanks again ! 
Wish you the Marry Christmas and prosperous New 2022 Year !
Best regards,
Serge
