### ISSUE TITLE
Error message after clicking bookmark window

### ISSUE THREAD

**Issue by wilmathome** [Dook1/Bookmarks-Dook#19]
Hi,

In version 3.0 x64 , after clicking in bookmark window, i get the following messages.

![image](https://user-images.githubusercontent.com/99897636/198877453-2a6576dd-ba2b-4ef4-ae1b-e46b471238d7.png)

![image](https://user-images.githubusercontent.com/99897636/198877471-803c844f-83c7-48eb-8005-4d2d57ebb657.png)

**Comment by Dook1** [comment]
Download again
https://github.com/Dook1/Bookmarks-Dook/releases/tag/3.0

**Comment by wilmathome** [comment]
That did it , Thanks !

Is it already possible to save a note ? I can't find how to do it .

**Comment by Dook1** [comment]
They are saved automatically.

**Comment by wilmathome** [comment]
What do i do wrong ?

![image](https://user-images.githubusercontent.com/99897636/198878613-cd1f7a8e-a9fc-417a-9157-81c6e0590aea.png)

**Comment by Dook1** [comment]
Long click on "Note" cell or Ctrl-Alt-F6 or Plugins->Bookmarks@Dook->Note

**Comment by wilmathome** [comment]
Sorry, should've found that, thanks again !!
