### ISSUE TITLE
Bookmarks-Dook makes Notepad++ periodic backup to stop working

### ISSUE THREAD

**Issue by carlos-cadu** [Dook1/Bookmarks-Dook#2]
Hi. I found you plugin great, but it makes periodic backup to stop working (Settings>Backup). So it became to leave the current session without save all files first (see screenshot attached). I had to uninstall Bookmarks-Dook because of that. 
Is this expected to happen, or is it a bug?
If you need further information, please let me know.

![notepad++_2019-10-28_09 33 17](https://user-images.githubusercontent.com/17261157/67678690-078a5f00-f966-11e9-95c2-332a38c6a8a0.png)

**Comment by Dook1** [comment]
I can't confirm the problem. I work in Notepad for almost 24 hours. Backup is done every 300sec. Moreover, I don't see any connection at all between my plugin and the backup.

**Comment by carlos-cadu** [comment]
Hi,
Thanks for replying.
I detailed the issue in this screen-recording, and as you can see the only
variable that could be causing the backup problem is the plugin:
http://bit.ly/36fDqLi
I`m using Notepad++ PORTABLE v7.8, but can confirm the problem also happens
with the previous v7.7.
If you need further information, please let me know.
Carlos

**Comment by Dook1** [comment]
Try to disable all other plugins.

**Comment by Dook1** [comment]
I think fixed in the latest version.
