### ISSUE TITLE
Wrong line on the top if some lines are folded

### ISSUE THREAD

**Issue by Iton-Horn** [Dook1/Bookmarks-Dook#21]
Hello, dear Bookmarks@Dook community!

I report following issue under Notepad++ v. 8.4.7 and Bookmark@Dook-plugin v. 3.0.0.

The v. 3.0.0 of the plugin brings the bookmarked line to the top of the document view.
It is very convinient. I would like to thank the author extra for this feature.

If an area is folded, clicking on a bookmark in bookmark panel does not bring the
bookmarked line to the top of the document view.

Steps to reproduce:
1. Create an empty file.au3 (its an AutoIt script file).
2. In the 1. line write "#cs" (without "", it is a mark for the start of a comment).
3. In the 11. line write "#ce" (without "", it is a mark for the end of a comment).
4. Make 50 - 100 new empty lines downwards.
5. Bring the document view to the top = the 1. line must be visible.
6. Set bookmarks on 1., 10., 15., 20., 25. line.
7. Fold the comment area - the area between 1. and 11. lines.
8. Do not click the bookmarks for 1. and 10. line - doing this will mask the described issue,
   the folded area must remaine folded.
9. Now try to bring the bookmarked 15., 20. or 25. line to the top of the document view
   by clicking bookmarks in bookmarks view.

**Comment by Dook1** [comment]
fixed in v3.1
