### ISSUE TITLE
Plug-in no longer works with new Notepad++

### ISSUE THREAD

**Issue by gskoczylas** [Dook1/Bookmarks-Dook#22]
It seems that the plug-in stopped working after one of the recent Notepad++ updates (I currently have version 8.4.7 64-bit).

I installed the new Notepad++ on a VM with Windows 10 Pro. Only the standard plugins are there. I added Bookmarks-Dook to them. I have verified that defining bookmarks does not display the bookmark panel. Furthermore, when I have displayed the bookmarks' panel via the plug-in menu, the panel is always empty and does not respond to defining or deleting new bookmarks.

**Comment by Dook1** [comment]
https://github.com/Dook1/Bookmarks-Dook/releases/tag/3.1

**Comment by gskoczylas** [comment]
Thanks! :-)

Unfortunately, the Plugins Admin does not show this version in the Updates tab.
