### ISSUE TITLE
how to get column header back??

### ISSUE THREAD

**Issue by Skrell** [Dook1/Bookmarks-Dook#24]
I accidentally remove the header provided to sort and widen/shrink the bookmark dook results and can't figure out how to get it back??

![image](https://user-images.githubusercontent.com/590266/205140742-8d4ba11c-bbda-4c0d-9e74-4da3c39f6510.png)

**Comment by Dook1** [comment]
Long right mouse click

**Comment by Skrell** [comment]
click where?  I tried everywhere I could think to click and nothing happened?

**Comment by Dook1** [comment]
Anywhere inside the panel. Hold down the right mouse button for more than 3 seconds.

**Comment by Skrell** [comment]
Got it thank you!!
