### ISSUE TITLE
Center bookmarks on screen upon click?

### ISSUE THREAD

**Issue by Skrell** [Dook1/Bookmarks-Dook#26]
LOVE this plugin, but found it annoying that every time I click a bookmark in your BookmarksDook window it put the line at the top of the screen... could you possibly add an option to center it in the file view?

**Comment by Dook1** [comment]
later

**Comment by darkworks** [comment]
yes this feature is also needed . maybe on job just add + 10 lines something like this

**Comment by Dook1** [comment]
As soon as I have free time

**Comment by darkworks** [comment]
+ can you pls add option to the plugin to restore the bookmark panel to default position i mean so that its attached it to bottom as sometime it get detached and act as new window and its hard to attach it back to the existing window.

maybe something like chrome dev tools 
![image](https://user-images.githubusercontent.com/12841788/215312590-63c53f4d-9d4f-450d-a64c-490a80c4ee99.png)

**Comment by Dook1** [comment]
The panel is never "sometimes" detached. You have to try hard to detach it. As for "hard to attach", contact the crooked NPP programmers who did it that way. 
Declined.

**Comment by Dook1** [comment]
added in v4.0.0

**Comment by darkworks** [comment]
> Owner

seems like v4.0.0 have problems cant arrange columns widths anymore  and also background color bookmark panel not working , its white  always

my note pad v8.4.6 x64

**Comment by Dook1** [comment]
1) right click on header->disable autowidth
or 
right click on header->settings->change autowidth for any or all columns
2) options->notepads colors off,   settings->color

**Comment by darkworks** [comment]
ok thanks disabled auto width no good.  however the color option is disable ?

![image](https://user-images.githubusercontent.com/12841788/224618862-15d3f67f-272f-4b0d-acb2-c9456fdf807d.png)

**Comment by Dook1** [comment]
Carefully reread paragraph two and do as it says.
