### ISSUE TITLE
Access violation in BookmarkDooks.dll

### ISSUE THREAD

**Issue by Iton-Horn** [Dook1/Bookmarks-Dook#27]
Hello, dear Notepad++ and Bookmarks-Dook Community!

I would like to report an error message
which occurs under Notepad++ v. 8.4.7 32 bit and Bookmarks-Dook-plugin v. 3.1.1
as shown in the attached jpg file.
Text: "Access violation at address 658C060F in module
'BookmarkDooks.dll'. Read of address 7C366C704.".

Steps to reproduce:
Not exactly known. I wrote a txt file in Notepad++ containing no bookmarks and clicked
outside of Notepad++ to open a txt file session for another txt file
by command line "notepad++ openSession session file".
The session opened in background. The described error message arrived after clicking a bookmark
in the txt file opened in this session.

Thank you.
Iton

![Access_violation](https://user-images.githubusercontent.com/91830481/208250307-30d56a67-1b7a-4135-8b9a-13d90cd9afdd.jpg)

**Comment by Dook1** [comment]
not reproducible

**Comment by Kimpa-Tammas** [comment]
An access violation exception for me, bookmarks panel open or not. Just open some files, then close all, one by one or all in once. The error box appears now.

![Clipboard 1](https://user-images.githubusercontent.com/33954530/209539245-e4b820f3-4d23-4f4e-8d75-d0b5355d7bb3.jpg)
