### ISSUE TITLE
not working in Notepad++ v8.4.7

### ISSUE THREAD

**Issue by oracloid** [Dook1/Bookmarks-Dook#28]
Hi.

Unfortunately, the plugin does not work in Notepad++ 8.4.7. As I understand it, this version introduced a new API for bookmarks. Now the list of bookmarks is not visible and when creating a new bookmark, the bookmark window closes.

**Comment by Dook1** [comment]
https://github.com/Dook1/Bookmarks-Dook/releases/tag/3.1.1
