### ISSUE TITLE
Sort options

### ISSUE THREAD

**Issue by Keyhabit** [Dook1/Bookmarks-Dook#29]
Hey. Once again, thanks for providing this great plugin!

Would it be possible to timestamp bookmarks with their creation date / time, have this information available as a column and then also to sort bookmarks by most recently created? So far, sorting by line number is the only option, right?

Cheers!

**Comment by Dook1** [comment]
Scintilla doesn't provide information about the bookmark's date.

**Comment by Keyhabit** [comment]
I see - and likely too much work to do this on the plugin side, i. e. store info as to when the bookmark was first visible to the plugin or some such.

**Comment by Dook1** [comment]
Exactly

**Comment by darkworks** [comment]
@Dook1 can you please add auto sort option to sort comments in Ascending order . in screenshot you can see its not in order, will be good if its sorted based on line number in Ascending order

![image](https://user-images.githubusercontent.com/12841788/231948719-9a8f3cda-f5d8-44e2-ac5a-753303e15e8b.png)

**Comment by Dook1** [comment]
Left click on column.
