### ISSUE TITLE
Different font and background colors for the Header/panel

### ISSUE THREAD

**Issue by zuntua** [Dook1/Bookmarks-Dook#30]
Using notepad++ 8.4.8 with Bookmarks@Dook 3.1.1
The color of the header is white and it can't be changed. The background of the panel can be customized and the font for both the header and the panel are identical. Consequently, it is difficult to find a good font color to contrast with the background panel color and the background header color. This makes it difficult to comfortably read the text in the panel or header. See images:
![Image 1](https://user-images.githubusercontent.com/121561998/210395362-86076604-c6a9-4f72-b535-1a2f00d506c8.jpg)
![Image 2](https://user-images.githubusercontent.com/121561998/210395474-8a4f87ca-3578-4e35-b8bf-6896d9722780.jpg)

Would it be possible to customize the background color of the header and independently set the color of the text in the panel and the header? Thanks!

**Comment by Dook1** [comment]
In the next release.

**Comment by Dook1** [comment]
added in v4.0.0
