### ISSUE TITLE
Bug: Can't reliably alter the bookmarks panel. Either an error message pops up or it doesn't save the changes after restarting notepad++

### ISSUE THREAD

**Issue by zuntua** [Dook1/Bookmarks-Dook#31]
When altering the bookmarks panel (eg enabling/disabling zebra, hiding/showing columns, altering the column width etc), an error message sometimes appears. For example:
![Error message 1](https://user-images.githubusercontent.com/121561998/210493750-1506df84-b5f6-4913-8793-7b509ec7ce3b.jpg)

Once this error message shows, any attempt to change anything in the bookmarks panel, the error message pops up again. The only way to resolve this (as far as I can figure out) is to close notepad++ and delete the `lv.dook` file and restart notepad++. After this, any changes to the bookmarks panel sometimes will occur without the error message popping up but the changes aren't saved after closing notepad++.

**Comment by Dook1** [comment]
This folder must be writable.

**Comment by Rom668** [comment]
Hello,
I think it's really what that message tells: No permission. Had the same issue with not saving prefs on one computer, which is win 10. "lv.dook" didn't even show up, so I compared it with other computer (win 11) and changed permissions of whole np++ folder. Now it works like charm. Didn't get the error message, though :) I really appreciate having "ini.files" in program dir but windows does not (%appdata% bla bla). "progam files" is so well protected, seems to be so much more possibly harmful to write an ini than executing a program, oh my.

**Comment by Rom668** [comment]
sorry dook1, too late :)

**Comment by Dook1** [comment]
Adding write permission to this folder does not affect security at all.

**Comment by Rom668** [comment]
:)

**Comment by zuntua** [comment]
Can `lv.dook` be create in `%appdata%\Notepad++\plugins\BookmarksDook` by default instead of `C:\Program Files\Notepad++\plugins\BookmarksDook`? That way the end user won't need to mess around with changing the write permission for `C:\Program Files\Notepad++\plugins\BookmarksDook`.

**Comment by Dook1** [comment]
Who do you represent here?  Who do you work for?  Why do you care about the end user?
 A smart "end user" installs the portable version in a separate folder with all access rights.

**Comment by Dook1** [comment]
The failure of yet another mediocre NPP agent.
