### ISSUE TITLE
Bookmark locations getting messed up

### ISSUE THREAD

**Issue by neviln** [Dook1/Bookmarks-Dook#32]
I absolutely LOVE your plugin and it has made my workflow so much more efficient. But as of the latest release (3.1.1), I appear to be experiencing some kind of issue with the plugin remembering the correct bookmark locations. 

For example, I have a large text file with over 100 bookmarks and it seems like whenever Notepad++ is shutdown suddenly (i.e. Windows crashing), all my bookmark locations (line numbers) shift by 2 or 3 lines when I re-open Notepad++. This issue **only** happens for the file that was active/in focus at the time of the crash. All other files that were open appear to keep their proper bookmark locations. 

So if I had a bookmark at line 11 and Notepad++ suddenly terminates, the location of that bookmark gets changed to line 9 or 8, but all my text stays in their original positions. I then have to then go and re-adjust each bookmark in that file. 

Not sure if there's anything I can do to prevent this from happening or if it has to be fixed in the coding. But any help is greatly appreciated.

**Comment by Dook1** [comment]
Notepad is responsible for saving the location of the bookmarks. My plugin has nothing to do with that.

**Comment by neviln** [comment]
Thank you so much for the very quick response :smile: 
Is there anything I could possibly do to prevent Notepad from incorrectly saving the bookmark locations for the active tab? Like running it in admin mode or any settings I can try changing, etc.. Or even anyway to correctly restore the proper bookmark locations the next time it happens, as it does take quite a bit of time to individually re-adjust all the bookmark locations manually.

**Comment by Dook1** [comment]
Try asking this question on the Notepad forum. I have not encountered such a problem.
