### ISSUE TITLE
[Feature Requirement] remember last status of header, note, line, filename

### ISSUE THREAD

**Issue by yangchihyuan** [Dook1/Bookmarks-Dook#33]
The version I am using is 3.1.1 (64bit), and my Notepad++ version is 8.4.9 (64bit).
For my convenience, I turn off the header, note, line, and filename regions in the bookmark panel. But when I re-open my Notepad++, the four regions are reset to on, and I need to manually turn them off again.
I am wondering whether those settings can be saved in the file C:\Users\Username\AppData\Roaming\Notepad++\plugins\config\BookmarksDook.ini, so that users do not need to modify those settings many times.

**Comment by Dook1** [comment]
https://github.com/Dook1/Bookmarks-Dook/issues/31#issuecomment-1370814204
