### ISSUE TITLE
Bookmarks@Dook doesn't update via Notepad++

### ISSUE THREAD

**Issue by neviln** [Dook1/Bookmarks-Dook#35]
Bookmarks@Dook shows up in the "Installed" tab of the Plugins Admin, but does not alert or recognize when there is an update available. I've had to manually download the plugin and update it myself the past 3 releases. Is there a setting I can change or something else I can do to make it update via Notepad++ like it used to before?
Thank you

**Comment by Dook1** [comment]
I don't have time for their moronic update procedures.

**Comment by neviln** [comment]
Is there another way to possibly be alerted when a new update is released?

**Comment by Dook1** [comment]
Watch->Custom->Releases

**Comment by neviln** [comment]
Thank you :)
