### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by neviln** [Dook1/Bookmarks-Dook#36]
Helllo, 
I know how little free time you currently have so I really appreciate you still releasing new versions of Bookmarks-Dook, but I was just wondering if there's any place where one can find out what's new or updated between versions. I tried to use the "compare" feature of Github so that I have to bother you, but for whatever reason, it keeps saying there were zero changes when I compared v4.02 to v4.01 and to v4.0....so I'm not sure if that feature is working properly or not.

Also, I was wondering if there is anyway to export the list of bookmarks I have created, just in case I lose them or if accidentally right-click one of the bookmarks. That way I can use the list to know where to place my bookmarks again.

Thanks again for all you do

**Comment by Dook1** [comment]
1) bug fixes
2) NPP is responsible for bookmark storage, so contact the NPP developers
