### ISSUE TITLE
Bookmarks@Dook not working

### ISSUE THREAD

**Issue by lpulido54** [Dook1/Bookmarks-Dook#37]
Hi. With the new version of Notepad++ v8.5.4 the plugging v2.3.3 is not working at all
![image](https://github.com/Dook1/Bookmarks-Dook/assets/44060501/3812bd19-ec85-4107-8c64-d9da77a31aa2)
I had changed some parameters without success.
![image](https://github.com/Dook1/Bookmarks-Dook/assets/44060501/3b4d6271-770e-4706-89b8-a42fc7f08996)
I'm using Windows 10 Pro
I really appreciate if someone can help me.
My best regards.

**Comment by Dook1** [comment]
https://github.com/Dook1/Bookmarks-Dook/releases/tag/v4.0.2

**Comment by lpulido54** [comment]
Thanks a lot!

My best regards.

---
Luis Pulido
I/S Senior Developer
Western Management, Inc.
The Conrad Companies
14577 Lorain Avenue
Cleveland, Ohio 44111
Phone: 216-941-3333 Ext. 1322
Fax: 1-440-848-8630
Email: ***@***.***

"Guess if you can, choose if you dare." ~ Pierre Corneille

On 2023-08-11 14:53, Dook1 wrote:

> https://github.com/Dook1/Bookmarks-Dook/releases/tag/v4.0.2
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/Dook1/Bookmarks-Dook/issues/37#issuecomment-1675225309
[2]
