### ISSUE TITLE
Invalid finename when I click ok or save in the setting dialog

### ISSUE THREAD

**Issue by yangchihyuan** [Dook1/Bookmarks-Dook#39]
Bookmarks@Dook version: 4.0.2 64bit
Notepad++ version: 8.5.7 64bit
Windows: 11 22H2
The folder D:\Program Files\Notepad++\plugins\BookmarksDook is writable (I installed Notepad++ in disk D:\)

![image](https://github.com/Dook1/Bookmarks-Dook/assets/11217467/3ac0bc83-ed23-4540-857f-c9a13744046a)
![image](https://github.com/Dook1/Bookmarks-Dook/assets/11217467/cd8082e7-af4e-4b77-a962-6f94e74c05af)
![image](https://github.com/Dook1/Bookmarks-Dook/assets/11217467/02499558-1ce0-4cdf-984f-d810312c98a0)

**Comment by Dook1** [comment]
1) Replace D:\Program Files\notepad++\plugins\BookmarksDook\BookmarksDook.dll  
https://github.com/Dook1/Bookmarks-Dook/releases/download/Debug/BookmarksDook.dll
2) Try save in the settings
3) Paste here: D:\Program Files\notepad++\notepad++.log

**Comment by yangchihyuan** [comment]
I replaced D:\Program Files\notepad++\plugins\BookmarksDook\BookmarksDook.dll with the downloaded BookmarksDook.dll (5864kb) and launched my Notepad++.
But I encoutered an error message, and the Bookmark@Dook item under the plugins menu disappered.
I turned off my Notepad++ and turned it on again, but still saw the error message dialog window.
![image](https://github.com/Dook1/Bookmarks-Dook/assets/11217467/9cc7247e-3504-458d-879b-2bab66d9ea2b)
![image](https://github.com/Dook1/Bookmarks-Dook/assets/11217467/ec17f795-c162-4c2f-80ab-e83b6b3dafc5)

**Comment by Dook1** [comment]
Upload here: D:\Program Files\notepad++\notepad++.log

**Comment by yangchihyuan** [comment]
But there is no file named notepad++.log
![image](https://github.com/Dook1/Bookmarks-Dook/assets/11217467/8fff29bf-4960-44e4-91fd-d32dde174a1b)

**Comment by Dook1** [comment]
D:\Program Files\Notepad++\  must be writable

**Comment by yangchihyuan** [comment]
After modifying the access right, I see a notepad++.log file
[notepad++.log](https://github.com/Dook1/Bookmarks-Dook/files/13069234/notepad%2B%2B.log)

**Comment by Dook1** [comment]
Try manually creating\copying any file in the folder D:\Program Files\Notepad++\plugins\BookmarksDook\Profiles\

**Comment by yangchihyuan** [comment]
There is no BookmarksDook\Profiles folder.
![螢幕擷取畫面 2023-10-25 051035](https://github.com/Dook1/Bookmarks-Dook/assets/11217467/becc4a80-1d0f-4330-8122-d83de47f7524)

I created the Profiles folder and a Test.docx Word file in it.
![螢幕擷取畫面 2023-10-25 051329](https://github.com/Dook1/Bookmarks-Dook/assets/11217467/4cf068cd-b331-4059-88d9-5e43b6c807f0)

But I still got the error message, even though I tried to change the filename.
![螢幕擷取畫面 2023-10-25 051313](https://github.com/Dook1/Bookmarks-Dook/assets/11217467/887b4a61-27ee-43cf-acd1-1d079b057bfa)

**Comment by Dook1** [comment]
fixed in 4.0.3
https://github.com/Dook1/Bookmarks-Dook/releases/tag/v4.0.3

**Comment by yangchihyuan** [comment]
ok. It works now.
