### ISSUE TITLE
Possibility to Change Background Color of the Bookmarks Tab

### ISSUE THREAD

**Issue by EldrinTaloc** [Dook1/Bookmarks-Dook#4]
Hi, Your plugin is just what I need, but could you add an option to edit the background color of the Bookmarks tab?

I use Notepad++ with the Deep Black Style, so it would be great if I could change the white background of the window into black.

**Comment by Dook1** [comment]
Added in 1.7
https://github.com/Dook1/Bookmarks-Dook/releases/tag/1.7.64b
https://github.com/Dook1/Bookmarks-Dook/releases/tag/1.7.32b

**Comment by EldrinTaloc** [comment]
Thank You Very Much
