### ISSUE TITLE
How to copy bookmarksDook table ?

### ISSUE THREAD

**Issue by elecherf** [Dook1/Bookmarks-Dook#42]
Hi,
Not sure, where to post this question for this great plugin.
Thank you

**Comment by Dook1** [comment]
For what purpose?

**Comment by elecherf** [comment]
Hi,

Let's imagine that you have a log like this with some bookmarks that are pointing to only relevant infos
![image](https://github.com/Dook1/Bookmarks-Dook/assets/10000902/ed88ee48-2b0f-49d6-ae19-ae3d520e28c6)

So the bookmarks panel view is: 
![image](https://github.com/Dook1/Bookmarks-Dook/assets/10000902/985641a8-f7a1-498b-9e8b-48df50efa34b)

Now, I want to make a report with only the relevant infos that i've pointed:
So, I would like to select the  column Text to the new report
![image](https://github.com/Dook1/Bookmarks-Dook/assets/10000902/c998a2cb-737a-4080-b633-11ab2dad6575)

Of course, the bookmark panel is an array with multiple columns with Line/Note/Text, so you may copy the full array as well.
And when you paste it, may be format the text, or use a special char to separate columns like csv format.

Thank you

**Comment by Dook1** [comment]
I asked what do you need it for?

**Comment by elecherf** [comment]
Use case is not enough clear ?

**Comment by Dook1** [comment]
I will try again.  For what purpose do you need this report?

**Comment by neviln** [comment]
Hi Dook, I don't think he's referring to any specific report. 
If I'm not misunderstanding, I think he's trying to say that if he had a log file (like in IMG 1), he was hoping to add bookmarks to only the lines he was interested in, and then be able to copy the list of bookmarked lines from the BookmarksDook panel (which he referred to as a report). Kind of like using your plugin a filter.

**Comment by Dook1** [comment]
Rejected. I don't see any point in that.
