### ISSUE TITLE
Request option to auto-sort columns/auto-group rows ?

### ISSUE THREAD

**Issue by Skrell** [Dook1/Bookmarks-Dook#44]
I love being able to sort my bookmarks by the different columns but I find that I'm constantly clicking to do it, would it be possible to add an option to auto-sort by line numbers but still keep filenames grouped together?

**Comment by Dook1** [comment]
1) Click on the "Filename" column header
2) Ctrl+Click on the "Text" column header

**Comment by Skrell** [comment]
> 1. Click on the "Filename" column header
> 2. Ctrl+Click on the "Text" column header

FANTASTIC!!!  This plugin keeps getting better!
