### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TheSQLGuru** [Dook1/Bookmarks-Dook#45]
Could you provide an option to show some context rows before and after the bookmark? This should be configurable as to how many before and after, and in the viewer panel it should provide an expandable view for each line that will present the context rows. Make it so that right-clicking or double-clicking the actual bookmark will take you there instead of expanding the view.

Also, I see that the current version is 4.xx, and the NP++ exposed version is 2.3.3. What are the feature changes between those builds (that is a LOT of changes!). 

Also, why can't we see the code for the plug-in? This makes it seem like the code may not be on the up-and-up...

**Comment by Dook1** [comment]
Denied.  This would require too many changes to the code.

> Also, why can't we see the code for the plug-in? This makes it seem like the code may not be on the up-and-up...

I don't care how it seems.
