### ISSUE TITLE
your help / documentation does not explain "Note" column

### ISSUE THREAD

**Issue by bendy101** [Dook1/Bookmarks-Dook#46]
as per my title, in the BookmarksDook window, there is a "Note" column - yet no explaination on how to add notes.

How do we add notes? The shortcut is not working.

**Comment by Dook1** [comment]
Download last release: https://github.com/Dook1/Bookmarks-Dook/releases/tag/v4.0.5
1. Select bookmark in bookmarks panel
2. Long click on Note cell or Plugins->Bookmarks@Dook->Note
