### ISSUE TITLE
[4.0.4] Broken "hide header".

### ISSUE THREAD

**Issue by wilkowy** [Dook1/Bookmarks-Dook#47]
Hiding "header" from panel results in losing access to "settings" and possibility to configure columns. This is not the same as "options" in menu.

Reinstalling plugin does not fix this bug.

Feature request: add possibility to show header again.

**Comment by Dook1** [comment]
Long right mouse click inside bookmarks panel.

**Comment by wilkowy** [comment]
> Long right mouse click inside bookmarks panel.

Thank you! It worked.

I was also able to fix this with WinSpy by removing HDS_HIDDEN for this control and then reenabling header.
