### ISSUE TITLE
Bookmarks panel does not track Notepad++ other view

### ISSUE THREAD

**Issue by davidbrigden** [Dook1/Bookmarks-Dook#6]
I sometimes  use Notepad++ Move to Other View function to have two files open side-by-side.  The Bookmark Panel doesn't recognize or react to the second view.   If I then close the tabs in the original view,  Bookmark still does not recognize/react to the bookmarks.

N++ Version:  7.9.1 (32bit)
Bookmarks@Dook Version:  2.1

Steps to Reproduce
1. Open fileA
2. open fileB
3.  Right-Click the tab for fileB and "Move to OtherView"
4.  Bookmark fileB (examine Bookmark panel and it does not react
5.  Close the tab for fileA.  fileB is still open and bookmarked.  Bookmark panel still does not react.
6.  Close fileB
7.  Open fileC and Bookmarks@dook is still doesn't react (almost.  Panel will still autohide when you add a bookmark)

Workaround to bring back functionality (beside restart of N++)
1.  Open a new file
2.  Right-Click the tab for fileC and "Move to Other View:  
3.  New file still doesn't react, but close that view.

**Comment by Dook1** [comment]
Ok. I am busy right now. I'll deal with this a little later.

**Comment by Dook1** [comment]
Try it:
https://github.com/Dook1/Bookmarks-Dook/releases/download/2.2.32b/BookmarksDook.32.2.2.zip
https://github.com/Dook1/Bookmarks-Dook/releases/download/2.2.64b/BookmarksDook.64.2.2.zip

**Comment by davidbrigden** [comment]
That fixed it.  Thank you.
