### ISSUE TITLE
Bookmark-Dook Panel - How to Use it?

### ISSUE THREAD

**Issue by cricrazy** [Dook1/Bookmarks-Dook#8]
I am a big fan on Bookmark Panel (Bookmarks-Dook) plugin. 

I have been using bookmark panel for a while. Being a **visual person** myself, I like to see how to plugin looks and behaves before actually installing it.  Recently, I added video of[ how to install and use Bookmark Panel ](https://youtu.be/QZH-wxHtpwI?t=327)for anyone wondering how the Bookmarks-Dook plugin works. 

It shows the following:
1. How to Install Bookmarks-Dook Plugin.
2. How to View/Switch between Bookmarks using the plugin. 

I am sharing a YouTube Video here. 

https://youtu.be/QZH-wxHtpwI?t=327

Hope others find it useful. (Disclaimer: I own this YouTube channel.)

Thanks.

**Comment by cricrazy** [comment]
This post is not a issue, but a help video document for any potential plugin users.

**Comment by Dook1** [comment]
Thanks. I added your video to the main page.

**Comment by cricrazy** [comment]
Awesome @Dook1. Thanks. Hope more people find it handy. Thank you for the plugin.
