### ISSUE TITLE
[Feature Request] Show Line Number

### ISSUE THREAD

**Issue by gamepad-coder** [Dook1/Bookmarks-Dook#9]
Bookmarks-Dook is an incredible plugin. Thanks!

# Feature Request:

Could you add an option to show the line number in the `Bookmarks Panel`?

# Potential Implementations:

## **1. Prepend the existing row's text with the line number and a ":" colon.**

**Example**

Assume that the `Bookmarks@Dook` Bookmarks Panel has the following content:  

   ```
   This is a bookmark on line 1.
   This is a bookmark on line 23.
   ```

If the user turns on `Show Line Numbers` in the options, this Bookmarks Panel would become: 

   ```
   1:   This is a bookmark on line 1.
   23:  This is a bookmark on line 23.
   ```

I'd be happy with even this much (with just the line number prepended, even if you don't format for spacing).

**However, this implementation has three drawbacks:** 

1. If the user renames the bookmark, the line number would potentially be erased.
2. Without a monospaced font and an algorithm to process leading spaces, the formatting for line numbers and content won't be as clean as the example above.
3. When lines are moved or newlines are inserted, each line number needs to be updated in the Bookmarks Panel. Similarly, if the user has `Show Line Numbers` enabled, then disables `Show Line Numbers`, each entry needs to be processed to remove the leading `##:  ` line number and colon.

**Assessment:**

The 2nd implementation below will probably be much easier. 

## **2. Add two columns, one for the line number, one for the bookmark text.**

If `Show Line Numbers` is disabled in the `Bookmarks@Dook` options menu, then the presentation can be exactly the same as it is currently, no alterations needed.

If `Show Line Numbers` is enabled in the `Bookmarks@Dook` options menu, then change the Bookmarks Panel to a display with two columns. 

For each bookmark entry's `1st column`:  
• Add the line number for the bookmark.

For each bookmark entry's `2nd column`:  
• Add the pre-existing bookmark text (potentially renamed already).

When lines are inserted or deleted, or newline characters are inserted or deleted, update the numbers in the `1st column`. 

When `Show Line Numbers` is enabled, then the user disables `Show Line Numbers`, hide the `1st column` and column headers.

## Closing Remarks

BookmarksDook is a **really** awesome extension for Notepad++, and should have been a built-in feature. I'm extremely grateful you made this. 

Hope you'll consider adding `Show Line Numbers`.

Thanks, and have a great day.

**Comment by Dook1** [comment]
And what is the line number for?

**Comment by gamepad-coder** [comment]
The line numbers which display in the left column of the main Notepad++ window, enabled via `Notepad++ Preferences -> Margins/Border/Edge -> Line Number -> Display`

&nbsp; 
With `Line Number -> Display` disabled:
![2021-03-26 18_29_30- Default  _new 1 - Notepad++](https://user-images.githubusercontent.com/65138515/112702436-73297200-8e61-11eb-9428-0ff9e287910b.png)

&nbsp; 
With `Line Number -> Display` enabled:

![2021-03-26 18_29_34- Default  _new 1 - Notepad++](https://user-images.githubusercontent.com/65138515/112702455-89373280-8e61-11eb-81de-959b83d0fa06.png)

&nbsp; 
Proposed functionality for Bookmarks Panel:

![2021-03-26 18_29_55- Default  _new 1 - Notepad++](https://user-images.githubusercontent.com/65138515/112702477-9522f480-8e61-11eb-8f8f-1fbef5ec5c8c.png)

**Comment by Dook1** [comment]
I meant, for which you need to know what the line number of the bookmark is

**Comment by gamepad-coder** [comment]
I work in large files, and line numbers help me remember which area of a file the line is from.

This is screenshot of a Notepad++ search result (for a file I'm working in right now).

![2021-03-27 12_25_24- Default  C__ autohotkey _util_ProgramLauncher_pl_gui_classes ahk - Notepad++](https://user-images.githubusercontent.com/65138515/112729041-2e9ce580-8ef8-11eb-8e6e-b0ad82dca96d.png)

The line number information just helps me stay oriented, and to know at a glance which part of the file the line is in.

This feature would be especially useful when I have many bookmarks (when multiple lines have similar text). 

<hr>

For more background, I'm also using the Analyse Plugin with Notepad++, which adds and removes bookmarks for search patterns Analyse finds (unrelated to the above screenshot).

This works really really well with BookmarksDook, which I use to go  through all the bookmarks Analyse creates.  

But sometimes when I have many many lines, I get disoriented and it takes time to find the area I'm looking for in BookmarksDook.

<hr>

My reasoning for this feature request:
- Bookmarks@Dook is the only bookmark dock plugin for Notepad++ in the Plugins Admin window.
- I'm guessing many people use Bookmarks@Dook
- I know a lot of programmers use Notepad++, so this would be useful to many people beyond just me.

Thanks for your time (even if you don't add this feature)  
and thanks for this plugin.

=)

**Comment by Dook1** [comment]
Ok. I'll do it, but a little later. 
Implementation №2.

**Comment by Dook1** [comment]
Try it:
https://github.com/Dook1/Bookmarks-Dook/releases/download/2.3.64b/BookmarksDook.64.2.3.zip
https://github.com/Dook1/Bookmarks-Dook/releases/download/2.3.32b/BookmarksDook.32.2.3.zip

I had to set the line numbers on the right, because otherwise I would have to change a lot of code.

**Comment by gamepad-coder** [comment]
Looks great!

I noticed that when I add a new bookmark,  
it updates all the line numbers (& also each entry's text) in the dock.

That's very awesome.

Thanks so much.

**Comment by gamepad-coder** [comment]
Visually, it's actually cleaner with the numbers on the right.  
So I'm totally happy with that choice.  

Especially if it was less for you to code.

This will save me so much time.
I **really** appreciate you doing this.

Thanks again, and have a wonderful day.
